application:
    environment:
        php:
            version: 5.6.0
build:
    environment:
        php: '5.6.0'

filter:
    paths:
        - 'src/*'
checks:
    php: true

coding_style:
    php:
        spaces:
            around_operators:
                concatenation: false
build_failure_conditions:
    - 'elements.rating(<= D).exists'
    - 'elements.rating(<= D).new.exists'


    - 'issues.label("coding-style").exists'
    - 'issues.label("coding-style").new.exists'

    - 'issues.label("coding-style").new.count > 5'
    - 'issues.severity(>= MAJOR).new.exists'

tools:
    external_code_coverage: false
    php_code_coverage: false
    php_sim:
        enabled: true
        min_mass: 16
    php_pdepend:
        enabled: true
        configuration_file: null
        suffixes:
            - php
    php_analyzer:
        enabled: true
        extensions:
            - php
    sensiolabs_security_checker:
        enabled: true
    php_changetracking:
        enabled: true
        bug_patterns:
            - '\bfix(?:es|ed)?\b'
        feature_patterns:
            - '\badd(?:s|ed)?\b'
            - '\bimplement(?:s|ed)?\b'